export default function TermsPage() {
  const sections = [
    {
      title: 'Using Atlas',
      body: 'By creating an account you agree to use Atlas for lawful learning purposes only, to keep your credentials secure, and to not resell access or abuse the credit system.',
    },
    {
      title: 'Billing & credits',
      body: 'Plans are billed monthly and include a set credit allowance each period. Unused credits do not roll over unless stated on your plan. Enterprise contracts may specify separate terms.',
    },
    {
      title: 'AI-generated content',
      body: 'Mentor responses are generated by AI and may occasionally be inaccurate. Atlas is a study companion, not a licensed substitute for professional advice in medicine, law, or finance.',
    },
    {
      title: 'Cancellation',
      body: 'You can cancel anytime from your account settings. Access continues until the end of the paid period. Refunds are handled per applicable store or Stripe policy.',
    },
  ];

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
      <h1 className="text-4xl font-extrabold tracking-tight text-slate-950 mb-2">
        Terms of Service
      </h1>
      <p className="text-sm text-slate-500 mb-10">Last updated: September 2026</p>

      <div className="space-y-8">
        {sections.map((section) => (
          <div key={section.title}>
            <h2 className="text-lg font-bold text-slate-950 mb-1.5">{section.title}</h2>
            <p className="text-sm text-slate-600 leading-relaxed">{section.body}</p>
          </div>
        ))}
        <p className="text-sm text-slate-600 leading-relaxed">
          Questions? Email{' '}
          <a href="mailto:legal@atlas.ai" className="font-semibold text-black underline">
            legal@atlas.ai
          </a>
          .
        </p>
      </div>
    </div>
  );
}